# Generated by Django 2.1.4 on 2018-12-14 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('areas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orgao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sugestao',
            fields=[
                ('cod_sugestao', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=60)),
                ('observacoes', models.CharField(max_length=200)),
                ('cod_area_conhecimento', models.ForeignKey(db_column='cod_area_conhecimento', null=True, on_delete=django.db.models.deletion.CASCADE, to='areas.Area_Conhecimento')),
                ('cod_orgao', models.ForeignKey(db_column='cod_orgao', null=True, on_delete=django.db.models.deletion.CASCADE, to='orgao.Orgao')),
                ('cod_usuario', models.ForeignKey(db_column='cod_usuario', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sugestao',
                'ordering': ['nome'],
            },
        ),
    ]
