# Generated by Django 2.2.6 on 2019-10-03 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area_Conhecimento',
            fields=[
                ('cod_area_conhecimento', models.AutoField(primary_key=True, serialize=False)),
                ('txt_descricao', models.CharField(max_length=200, unique=True)),
                ('ind_excluido', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'area_conhecimento',
                'ordering': ['txt_descricao'],
            },
        ),
    ]
