# Generated by Django 2.1.4 on 2018-12-14 18:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modalidade', '0001_initial'),
        ('plano', '0001_initial'),
        ('areas', '0001_initial'),
        ('orgao', '0001_initial'),
        ('capacitaApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tipo_treinamento', '0001_initial'),
        ('objetivos', '0001_initial'),
        ('treinamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Necessidade',
            fields=[
                ('cod_necessidade', models.AutoField(primary_key=True, serialize=False)),
                ('txt_descricao', models.CharField(max_length=200, null=True)),
                ('hor_duracao', models.DecimalField(decimal_places=0, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('qtd_servidor', models.DecimalField(decimal_places=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('justificativa', models.CharField(max_length=300)),
                ('aprovado', models.NullBooleanField(default=False)),
                ('ind_excluido', models.NullBooleanField(default=False)),
                ('cod_area_conhecimento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='areas.Area_Conhecimento')),
                ('cod_modalidade', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='modalidade.Modalidade_Treinamento')),
            ],
            options={
                'db_table': 'necessidade',
                'ordering': ['cod_area_conhecimento', 'cod_treinamento'],
            },
        ),
        migrations.CreateModel(
            name='Necessidade_Orgao',
            fields=[
                ('cod_necessidade_orgao', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=False)),
                ('importado', models.BooleanField(default=False)),
                ('cod_orgao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgao.Orgao')),
                ('cod_plano_capacitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plano.Plano_Capacitacao')),
            ],
            options={
                'db_table': 'necessidade_orgao',
            },
        ),
        migrations.AddField(
            model_name='necessidade',
            name='cod_necessidade_orgao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='necessidade.Necessidade_Orgao'),
        ),
        migrations.AddField(
            model_name='necessidade',
            name='cod_nivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='capacitaApp.Nivel'),
        ),
        migrations.AddField(
            model_name='necessidade',
            name='cod_objetivo_treinamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='objetivos.Objetivo_Treinamento'),
        ),
        migrations.AddField(
            model_name='necessidade',
            name='cod_prioridade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='capacitaApp.Prioridade'),
        ),
        migrations.AddField(
            model_name='necessidade',
            name='cod_tipo_treinamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tipo_treinamento.Tipo_Treinamento'),
        ),
        migrations.AddField(
            model_name='necessidade',
            name='cod_treinamento',
            field=models.ForeignKey(default='-1', on_delete=django.db.models.deletion.DO_NOTHING, to='treinamento.Treinamento'),
        ),
        migrations.AddField(
            model_name='necessidade',
            name='cod_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
