# Generated by Django 2.1.4 on 2018-12-19 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('necessidade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='necessidade',
            name='cod_treinamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='treinamento.Treinamento'),
        ),
    ]
