# Generated by Django 2.2.6 on 2019-10-04 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('necessidade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='necessidade',
            name='cod_area_conhecimento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='areas.Area_Conhecimento'),
        ),
    ]
