# Generated by Django 2.1.4 on 2018-12-20 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('necessidade', '0002_auto_20181219_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='necessidade',
            name='cod_treinamento',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.DO_NOTHING, to='treinamento.Treinamento'),
        ),
    ]
