# Generated by Django 2.2.6 on 2019-10-04 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('necessidade', '0002_auto_20191004_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='necessidade',
            name='cod_area_conhecimento',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.DO_NOTHING, to='areas.Area_Conhecimento'),
            preserve_default=False,
        ),
    ]
