# Generated by Django 2.1.4 on 2018-12-26 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('necessidade', '0004_auto_20181226_1634'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='necessidade',
            options={'ordering': ['cod_area_conhecimento', 'cod_treinamento', 'cod_necessidade']},
        ),
    ]
