# Generated by Django 2.1.4 on 2019-02-15 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('necessidade', '0005_auto_20181226_1638'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='necessidade',
            options={'ordering': ['cod_area_conhecimento', 'cod_treinamento', 'cod_modalidade', 'cod_nivel', 'hor_duracao', 'cod_tipo_treinamento', 'cod_prioridade', 'cod_objetivo_treinamento']},
        ),
    ]
