# Generated by Django 2.2.6 on 2019-10-03 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('necessidade', '0007_auto_20190215_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='necessidade',
            name='ementa',
            field=models.TextField(default='Sem descrição'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='necessidade',
            name='treinamento_externo',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='necessidade',
            name='valor_estimado',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='necessidade',
            name='aprovado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='necessidade',
            name='ind_excluido',
            field=models.BooleanField(default=False),
        ),
    ]
