# Generated by Django 2.2.6 on 2019-10-03 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgao', '0002_auto_20191003_1034'),
        ('necessidade', '0008_auto_20191003_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='necessidade',
            name='cod_orgao_origem',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='orgao.Orgao'),
            preserve_default=False,
        ),
    ]
