# Generated by Django 2.2.6 on 2019-10-03 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modalidade_Treinamento',
            fields=[
                ('cod_modalidade', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('ind_excluido', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'modalidade_treinamento',
                'ordering': ['nome'],
            },
        ),
    ]
