# Generated by Django 2.1.4 on 2018-12-14 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orgao',
            fields=[
                ('cod_orgao', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200, unique=True)),
                ('ind_excluido', models.NullBooleanField(default=False)),
                ('cod_superior', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='orgao.Orgao')),
            ],
            options={
                'db_table': 'orgao',
                'ordering': ['nome'],
            },
        ),
    ]
