# Generated by Django 2.2.6 on 2019-10-04 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgao',
            name='nivel',
            field=models.IntegerField(default=-1),
        ),
    ]
