# Generated by Django 2.0.7 on 2018-07-11 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novo_capacita', '0002_auto_20180710_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano_capacitacao',
            name='qtd_servidores_comissionados',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plano_capacitacao',
            name='qtd_servidores_efetivos',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plano_capacitacao',
            name='situacao',
            field=models.CharField(default=21, max_length=200),
            preserve_default=False,
        ),
    ]
