# Generated by Django 2.0.7 on 2018-07-13 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novo_capacita', '0003_auto_20180711_1015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipo_plano_capacitacao',
            old_name='nom_tipo_plano_capacitacao',
            new_name='nome_tipo_plano_capacitacao',
        ),
    ]
