# Generated by Django 2.0.7 on 2018-07-31 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novo_capacita', '0006_sub_area_conhecimento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sub_area_conhecimento',
            old_name='cod_area_conhecimento',
            new_name='cod_area_conhecimento_id',
        ),
    ]
