# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-03 12:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novo_capacita', '0008_auto_20180731_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='necessidade',
            name='cod_area_conhecimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novo_capacita.Sub_Area_Conhecimento'),
        ),
    ]
