# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-03 12:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novo_capacita', '0009_auto_20180803_0937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='necessidade',
            old_name='cod_area_conhecimento',
            new_name='cod_sub_area_conhecimento',
        ),
    ]
