# Generated by Django 2.2.6 on 2019-10-03 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plano_Capacitacao',
            fields=[
                ('cod_plano_capacitacao', models.AutoField(primary_key=True, serialize=False)),
                ('ano_plano_capacitacao', models.DecimalField(decimal_places=0, max_digits=4, unique=True)),
                ('plano_habilitado', models.BooleanField()),
                ('ind_excluido', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'plano_capacitacao',
                'ordering': ['ano_plano_capacitacao'],
            },
        ),
    ]
