# Generated by Django 2.1.1 on 2018-09-21 02:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area_Conhecimento',
            fields=[
                ('cod_area_conhecimento', models.AutoField(primary_key=True, serialize=False)),
                ('txt_descricao', models.CharField(max_length=200)),
                ('ind_excluido', models.DecimalField(decimal_places=0, default=0, max_digits=2)),
            ],
            options={
                'managed': False,
                'db_table': 'Area_Conhecimento',
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'managed': False,
                'db_table': 'auth_group',
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
                'db_table': 'auth_group_permissions',
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'managed': False,
                'db_table': 'auth_permission',
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'auth_user',
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
                'db_table': 'auth_user_groups',
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
                'db_table': 'auth_user_user_permissions',
            },
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('cod_avaliacao', models.AutoField(primary_key=True, serialize=False)),
                ('valor_custo', models.DecimalField(decimal_places=2, max_digits=17)),
                ('ind_excluido', models.DecimalField(decimal_places=0, default=0, max_digits=2)),
            ],
            options={
                'managed': False,
                'db_table': 'Avaliacao',
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'managed': False,
                'db_table': 'django_admin_log',
            },
        ),
        migrations.CreateModel(
            name='DjangoCasNgProxygrantingticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=255, null=True)),
                ('pgtiou', models.CharField(blank=True, max_length=255, null=True)),
                ('pgt', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateTimeField()),
            ],
            options={
                'managed': False,
                'db_table': 'django_cas_ng_proxygrantingticket',
            },
        ),
        migrations.CreateModel(
            name='DjangoCasNgSessionticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=255)),
                ('ticket', models.CharField(max_length=255)),
            ],
            options={
                'managed': False,
                'db_table': 'django_cas_ng_sessionticket',
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'managed': False,
                'db_table': 'django_content_type',
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'managed': False,
                'db_table': 'django_migrations',
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'managed': False,
                'db_table': 'django_session',
            },
        ),
        migrations.CreateModel(
            name='Iniciativa',
            fields=[
                ('cod_iniciativa', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
            ],
            options={
                'managed': False,
                'db_table': 'Iniciativa',
            },
        ),
        migrations.CreateModel(
            name='Mes',
            fields=[
                ('cod_mes', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
            ],
            options={
                'managed': False,
                'db_table': 'Mes',
            },
        ),
        migrations.CreateModel(
            name='Necessidade',
            fields=[
                ('cod_necessidade', models.AutoField(primary_key=True, serialize=False)),
                ('txt_descricao', models.CharField(max_length=200)),
                ('qtd_servidor', models.DecimalField(decimal_places=0, max_digits=6)),
                ('hor_duracao', models.DecimalField(decimal_places=0, max_digits=2)),
                ('ind_excluido', models.DecimalField(decimal_places=0, default=0, max_digits=2)),
            ],
            options={
                'managed': False,
                'db_table': 'Necessidade',
            },
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('cod_nivel', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
            ],
            options={
                'managed': False,
                'db_table': 'Nivel',
            },
        ),
        migrations.CreateModel(
            name='Orgao',
            fields=[
                ('cod_orgao', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
            ],
            options={
                'managed': False,
                'db_table': 'Orgao',
            },
        ),
        migrations.CreateModel(
            name='Permissao',
            fields=[
                ('cod_permissao', models.AutoField(primary_key=True, serialize=False)),
                ('ano_plano_capacitacao', models.DecimalField(decimal_places=0, max_digits=4)),
            ],
            options={
                'managed': False,
                'db_table': 'Permissao',
            },
        ),
        migrations.CreateModel(
            name='Plano_Capacitacao',
            fields=[
                ('cod_plano_capacitacao', models.AutoField(primary_key=True, serialize=False)),
                ('situacao', models.CharField(max_length=200)),
                ('qtd_servidores_efetivos', models.IntegerField()),
                ('qtd_servidores_comissionados', models.IntegerField()),
                ('ano_plano_capacitacao', models.DecimalField(decimal_places=0, max_digits=4)),
                ('ind_excluido', models.DecimalField(decimal_places=0, default=0, max_digits=2)),
            ],
            options={
                'managed': False,
                'db_table': 'Plano_Capacitacao',
            },
        ),
        migrations.CreateModel(
            name='Prioridade',
            fields=[
                ('cod_prioridade', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
            ],
            options={
                'managed': False,
                'db_table': 'Prioridade',
            },
        ),
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('cod_secretaria', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
            ],
            options={
                'managed': False,
                'db_table': 'Secretaria',
            },
        ),
        migrations.CreateModel(
            name='Sub_Area_Conhecimento',
            fields=[
                ('cod_sub_area_conhecimento', models.AutoField(primary_key=True, serialize=False)),
                ('txt_descricao', models.CharField(max_length=200)),
                ('ind_excluido', models.DecimalField(decimal_places=0, default=0, max_digits=2)),
            ],
            options={
                'managed': False,
                'db_table': 'Sub_Area_Conhecimento',
            },
        ),
        migrations.CreateModel(
            name='Tipo_Plano_Capacitacao',
            fields=[
                ('cod_tipo_plano_capacitacao', models.AutoField(primary_key=True, serialize=False)),
                ('sgl_tipo_plano_capacitacao', models.CharField(max_length=6)),
                ('nome_tipo_plano_capacitacao', models.CharField(max_length=200)),
                ('ind_excluido', models.DecimalField(decimal_places=0, default=0, max_digits=2, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'Tipo_Plano_Capacitacao',
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('cod_turno', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
            ],
            options={
                'managed': False,
                'db_table': 'Turno',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titular', models.BooleanField(null=True)),
                ('permissao_necessidade', models.BooleanField(null=True)),
                ('orgao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='capacita.Orgao')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
