# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-11 18:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('capacita', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area_Conhecimento',
            fields=[
                ('cod_area_conhecimento', models.AutoField(primary_key=True, serialize=False)),
                ('txt_descricao', models.CharField(max_length=200)),
                ('ind_excluido', models.DecimalField(decimal_places=0, default=0, max_digits=2)),
            ],
            options={
                'db_table': 'Area_Conhecimento',
            },
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('cod_avaliacao', models.AutoField(primary_key=True, serialize=False)),
                ('valor_custo', models.DecimalField(decimal_places=2, max_digits=17)),
                ('ind_excluido', models.DecimalField(decimal_places=0, default=0, max_digits=2)),
            ],
            options={
                'db_table': 'Avaliacao',
            },
        ),
        migrations.CreateModel(
            name='Iniciativa',
            fields=[
                ('cod_iniciativa', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Iniciativa',
            },
        ),
        migrations.CreateModel(
            name='Mes',
            fields=[
                ('cod_mes', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Mes',
            },
        ),
        migrations.CreateModel(
            name='Necessidade',
            fields=[
                ('cod_necessidade', models.AutoField(primary_key=True, serialize=False)),
                ('txt_descricao', models.CharField(max_length=200)),
                ('qtd_servidor', models.DecimalField(decimal_places=0, max_digits=6)),
                ('hor_duracao', models.DecimalField(decimal_places=0, max_digits=2)),
                ('ind_excluido', models.DecimalField(decimal_places=0, default=0, max_digits=2)),
                ('cod_iniciativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacita.Iniciativa')),
                ('cod_mes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacita.Mes')),
            ],
            options={
                'db_table': 'Necessidade',
            },
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('cod_nivel', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Nivel',
            },
        ),
        migrations.CreateModel(
            name='Orgao',
            fields=[
                ('cod_orgao', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Orgao',
            },
        ),
        migrations.CreateModel(
            name='Permissao',
            fields=[
                ('cod_permissao', models.AutoField(primary_key=True, serialize=False)),
                ('ano_plano_capacitacao', models.DecimalField(decimal_places=0, max_digits=4)),
            ],
            options={
                'db_table': 'Permissao',
            },
        ),
        migrations.CreateModel(
            name='Plano_Capacitacao',
            fields=[
                ('cod_plano_capacitacao', models.AutoField(primary_key=True, serialize=False)),
                ('situacao', models.CharField(max_length=200)),
                ('qtd_servidores_efetivos', models.IntegerField()),
                ('qtd_servidores_comissionados', models.IntegerField()),
                ('ano_plano_capacitacao', models.DecimalField(decimal_places=0, max_digits=4)),
                ('ind_excluido', models.DecimalField(decimal_places=0, default=0, max_digits=2)),
                ('cod_orgao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacita.Orgao')),
            ],
            options={
                'db_table': 'Plano_Capacitacao',
            },
        ),
        migrations.CreateModel(
            name='Prioridade',
            fields=[
                ('cod_prioridade', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Prioridade',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titular', models.BinaryField()),
                ('orgao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacita.Orgao')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('cod_secretaria', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Secretaria',
            },
        ),
        migrations.CreateModel(
            name='Sub_Area_Conhecimento',
            fields=[
                ('cod_sub_area_conhecimento', models.AutoField(primary_key=True, serialize=False)),
                ('txt_descricao', models.CharField(max_length=200)),
                ('ind_excluido', models.DecimalField(decimal_places=0, default=0, max_digits=2)),
                ('cod_area_conhecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacita.Area_Conhecimento')),
            ],
            options={
                'db_table': 'Sub_Area_Conhecimento',
            },
        ),
        migrations.CreateModel(
            name='Tipo_Plano_Capacitacao',
            fields=[
                ('cod_tipo_plano_capacitacao', models.AutoField(primary_key=True, serialize=False)),
                ('sgl_tipo_plano_capacitacao', models.CharField(max_length=6)),
                ('nome_tipo_plano_capacitacao', models.CharField(max_length=200)),
                ('ind_excluido', models.DecimalField(decimal_places=0, default=0, max_digits=2)),
            ],
            options={
                'db_table': 'Tipo_Plano_Capacitacao',
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('cod_turno', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Turno',
            },
        ),
        migrations.DeleteModel(
            name='Acao',
        ),
        migrations.AddField(
            model_name='plano_capacitacao',
            name='cod_tipo_plano_capacitacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacita.Tipo_Plano_Capacitacao'),
        ),
        migrations.AddField(
            model_name='permissao',
            name='cod_secretaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacita.Secretaria'),
        ),
        migrations.AddField(
            model_name='permissao',
            name='cod_tipo_plano_capacitacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacita.Tipo_Plano_Capacitacao'),
        ),
        migrations.AddField(
            model_name='necessidade',
            name='cod_nivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacita.Nivel'),
        ),
        migrations.AddField(
            model_name='necessidade',
            name='cod_plano_capacitacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacita.Plano_Capacitacao'),
        ),
        migrations.AddField(
            model_name='necessidade',
            name='cod_prioridade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacita.Prioridade'),
        ),
        migrations.AddField(
            model_name='necessidade',
            name='cod_sub_area_conhecimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacita.Sub_Area_Conhecimento'),
        ),
        migrations.AddField(
            model_name='necessidade',
            name='cod_turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacita.Turno'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='cod_necessidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacita.Necessidade'),
        ),
    ]
