# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-11 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacita', '0002_auto_20180911_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='titular',
            field=models.BinaryField(null=True),
        ),
    ]
