# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-16 19:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capacita', '0002_auto_20180710_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sub_Area_Conhecimento',
            fields=[
                ('cod_sub_area_conhecimento', models.AutoField(primary_key=True, serialize=False)),
                ('txt_descricao', models.CharField(max_length=200)),
                ('ind_excluido', models.DecimalField(decimal_places=0, default=0, max_digits=2)),
                ('cod_area_conhecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacita.Area_Conhecimento')),
            ],
            options={
                'db_table': 'Sub_Area_Conhecimento',
            },
        ),
        migrations.RemoveField(
            model_name='necessidade',
            name='cod_area_conhecimento',
        ),
        migrations.RemoveField(
            model_name='tipo_plano_capacitacao',
            name='nom_tipo_plano_capacitacao',
        ),
        migrations.AddField(
            model_name='plano_capacitacao',
            name='qtd_servidores_comissionados',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plano_capacitacao',
            name='qtd_servidores_efetivos',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plano_capacitacao',
            name='situacao',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipo_plano_capacitacao',
            name='nome_tipo_plano_capacitacao',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='necessidade',
            name='cod_sub_area_conhecimento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='capacita.Sub_Area_Conhecimento'),
            preserve_default=False,
        ),
    ]
