# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-11 18:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capacita', '0003_auto_20180911_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='orgao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='capacita.Orgao'),
        ),
    ]
