# Generated by Django 2.0.7 on 2018-07-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacita', '0004_auto_20180713_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_plano_capacitacao',
            name='nome_tipo_plano_capacitacao',
            field=models.CharField(max_length=200),
        ),
    ]
