# Generated by Django 2.0.7 on 2018-07-30 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capacita', '0005_auto_20180720_0910'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sub_Area_Conhecimento',
            fields=[
                ('cod_sub_area_conhecimento', models.AutoField(primary_key=True, serialize=False)),
                ('txt_descricao', models.CharField(max_length=200)),
                ('ind_excluido', models.DecimalField(decimal_places=0, default=0, max_digits=2)),
                ('cod_area_conhecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacita.Area_Conhecimento')),
            ],
            options={
                'db_table': 'Sub_Area_Conhecimento',
            },
        ),
    ]
