# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-16 19:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capacita', '0003_auto_20180816_1619'),
        ('capacita', '0010_auto_20180803_0938'),
    ]

    operations = [
    ]
