# Generated by Django 2.1.3 on 2018-11-27 19:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoCasNgProxygrantingticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=255, null=True)),
                ('pgtiou', models.CharField(blank=True, max_length=255, null=True)),
                ('pgt', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_cas_ng_proxygrantingticket',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoCasNgSessionticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=255)),
                ('ticket', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'django_cas_ng_sessionticket',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Area_Conhecimento',
            fields=[
                ('cod_area_conhecimento', models.AutoField(primary_key=True, serialize=False)),
                ('txt_descricao', models.CharField(max_length=200, unique=True)),
                ('ind_excluido', models.NullBooleanField(default=False)),
            ],
            options={
                'db_table': 'area_conhecimento',
                'ordering': ['txt_descricao'],
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('cod_evento', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=60, unique=True)),
                ('ind_excluido', models.NullBooleanField(default=False)),
            ],
            options={
                'db_table': 'evento',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Modalidade_Treinamento',
            fields=[
                ('cod_modalidade', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('ind_excluido', models.NullBooleanField(default=False)),
            ],
            options={
                'db_table': 'modalidade_treinamento',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Necessidade',
            fields=[
                ('cod_necessidade', models.AutoField(primary_key=True, serialize=False)),
                ('txt_descricao', models.CharField(max_length=200, null=True)),
                ('hor_duracao', models.DecimalField(decimal_places=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0)])),
                ('qtd_servidor', models.DecimalField(decimal_places=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('justificativa', models.CharField(max_length=300)),
                ('aprovado', models.NullBooleanField(default=False)),
                ('ind_excluido', models.NullBooleanField(default=False)),
                ('cod_area_conhecimento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='capacitaApp.Area_Conhecimento')),
                ('cod_evento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='capacitaApp.Evento')),
                ('cod_modalidade', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='capacitaApp.Modalidade_Treinamento')),
            ],
            options={
                'db_table': 'necessidade',
                'ordering': ['cod_area_conhecimento', 'cod_treinamento'],
            },
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('cod_nivel', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200, unique=True)),
                ('ind_excluido', models.NullBooleanField(default=False)),
            ],
            options={
                'db_table': 'nivel',
            },
        ),
        migrations.CreateModel(
            name='Objetivo_Treinamento',
            fields=[
                ('cod_objetivo_treinamento', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150, unique=True)),
                ('ind_excluido', models.NullBooleanField(default=False)),
            ],
            options={
                'db_table': 'objetivo_treinamento',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Orgao',
            fields=[
                ('cod_orgao', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200, unique=True)),
                ('ind_excluido', models.NullBooleanField(default=False)),
            ],
            options={
                'db_table': 'orgao',
            },
        ),
        migrations.CreateModel(
            name='Permissao',
            fields=[
                ('cod_permissao', models.AutoField(primary_key=True, serialize=False)),
                ('ano_plano_capacitacao', models.DecimalField(decimal_places=0, max_digits=4)),
                ('cod_orgao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='capacitaApp.Orgao')),
            ],
            options={
                'db_table': 'permissao',
            },
        ),
        migrations.CreateModel(
            name='Plano_Capacitacao',
            fields=[
                ('cod_plano_capacitacao', models.AutoField(primary_key=True, serialize=False)),
                ('ano_plano_capacitacao', models.DecimalField(decimal_places=0, max_digits=4, unique=True)),
                ('plano_habilitado', models.NullBooleanField()),
                ('ind_excluido', models.NullBooleanField(default=False)),
            ],
            options={
                'db_table': 'plano_capacitacao',
            },
        ),
        migrations.CreateModel(
            name='Prioridade',
            fields=[
                ('cod_prioridade', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200, unique=True)),
                ('ind_excluido', models.NullBooleanField(default=False)),
            ],
            options={
                'db_table': 'prioridade',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permissao_necessidade', models.NullBooleanField(default=False)),
                ('orgao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='capacitaApp.Orgao')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'capacita_profile',
            },
        ),
        migrations.CreateModel(
            name='Tipo_Treinamento',
            fields=[
                ('cod_tipo_treinamento', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=900, unique=True)),
                ('ind_excluido', models.NullBooleanField(default=False)),
            ],
            options={
                'db_table': 'tipo_treinamento',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Treinamento',
            fields=[
                ('cod_treinamento', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=900, unique=True)),
                ('ind_excluido', models.NullBooleanField(default=False)),
                ('cod_area_conhecimento', models.ForeignKey(default='0', on_delete=django.db.models.deletion.DO_NOTHING, to='capacitaApp.Area_Conhecimento')),
            ],
            options={
                'db_table': 'treinamento',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='necessidade',
            name='cod_nivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='capacitaApp.Nivel'),
        ),
        migrations.AddField(
            model_name='necessidade',
            name='cod_objetivo_treinamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='capacitaApp.Objetivo_Treinamento'),
        ),
        migrations.AddField(
            model_name='necessidade',
            name='cod_orgao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='capacitaApp.Orgao'),
        ),
        migrations.AddField(
            model_name='necessidade',
            name='cod_plano_capacitacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='capacitaApp.Plano_Capacitacao'),
        ),
        migrations.AddField(
            model_name='necessidade',
            name='cod_prioridade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='capacitaApp.Prioridade'),
        ),
        migrations.AddField(
            model_name='necessidade',
            name='cod_tipo_treinamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='capacitaApp.Tipo_Treinamento'),
        ),
        migrations.AddField(
            model_name='necessidade',
            name='cod_treinamento',
            field=models.ForeignKey(default='-1', on_delete=django.db.models.deletion.DO_NOTHING, to='capacitaApp.Treinamento'),
        ),
        migrations.AddField(
            model_name='necessidade',
            name='cod_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
