# Generated by Django 2.2.6 on 2019-10-30 18:35

from django.db import migrations, models
import django.db.models.deletion


def cria_tipos_notificacao(apps, schema_editor):
    TipoNotificacao = apps.get_model("capacitaApp", "TipoNotificacao")
    TipoNotificacao.objects.bulk_create([
        TipoNotificacao(descricao="Aproximação do Prazo"),
        TipoNotificacao(descricao="Aumento de Prazo"),
    ])


def cria_tipos_destinatarios(apps, schema_editor):
    TipoDestinatarios = apps.get_model("capacitaApp", "TipoDestinatarios")
    TipoDestinatarios.objects.bulk_create([
        TipoDestinatarios(descricao="Todos os Órgãos"),
        TipoDestinatarios(descricao="Apenas Órgãos Nível 1"),
        TipoDestinatarios(descricao="Apenas Órgãos Níveis 1 e 2"),
    ])


def cria_notificacoes(apps, schema_editor):
    Notificacao = apps.get_model("capacitaApp", "Notificacao")
    Notificacao.objects.bulk_create([
        Notificacao(
            tipo_id=1,
            remetente="capacita_suporte@interlegis.leg.br",
            destinatarios_id=1,
            cc='',
            assunto="Lembrete: encerramento do prazo para pedidos de capacitação se aproximando.",
            mensagem="""Prezados,\n\nVenho respeitosamente lembrar-lhes que se encerra nesta sexta-feira, 18/10/2019, o prazo para envio de pedidos de capacitação para o ILB, os quais servirão de insumos para a elaboração do Plano de Capacitação e Desenvolvimento dos Servidores do Senado Federal (PCASF) para o ano de 2020.\n\nAssim sendo, caso tenham quaisquer demandas de capacitação para membros de suas equipes (inclusive participação em eventos, congressos, seminários, etc), peço-lhes a gentileza de acessar nossa plataforma Capacita, disponível em https://capacita.interlegis.leg.br, para registrar as atividades desejadas.\n\nEstão autorizados a usar o sistema todos os chefes de serviço, coordenadores e diretores de secretaria, sendo que as demandas apresentadas por cada um devem ser aprovadas pelos órgãos superiores, até chegar ao titular da secretaria, que tem a prerrogativa do envio ao ILB das demandas por ele ratificadas.\n\nEm caso de substituição ou ausência do titular da unidade, ou mesmo do interesse de delegação deste preenchimento para outro servidor, favor entrar em contato pelo e-mail capacita_suporte@interlegis.leg.br para que possamos providenciar a autorização.\n\nAlgumas orientações para uso do sistema podem ser vistas em https://capacita.interlegis.leg.br/manual. Em caso de dúvidas, também estou disponível no ramal 5962.\n\nAtenciosamente\n\nMatheus Garcia Barbosa de Figueiredo\nAnalista de Sistemas - Tel (61) 3303-5962\nServiço de Pesquisa e Desenvolvimento Tecnológico - SPDT\nCoordenação de Tecnologia da Informação - COTIN\nSenado Federal / ILB / Interlegis"""),
        Notificacao(
            tipo_id=2,
            remetente="capacita_suporte@interlegis.leg.br",
            destinatarios_id=1,
            cc='',
            assunto="Aviso: prorrogação do prazo para pedidos de capacitação.",
            mensagem="""Prezados,\n\nVenho respeitosamente avisar-lhes que foi prorrogado para [DIA-DA-SEMANA], [DATA-DO-NOVO-PRAZO], o prazo para envio de pedidos de capacitação para o ILB, os quais servirão de insumos para a elaboração do Plano de Capacitação e Desenvolvimento dos Servidores do Senado Federal (PCASF) para o ano de 2020.\n\nAssim sendo, caso tenham quaisquer demandas de capacitação para membros de suas equipes (inclusive participação em eventos, congressos, seminários, etc), peço-lhes a gentileza de acessar nossa plataforma Capacita, disponível em https://capacita.interlegis.leg.br, para registrar as atividades desejadas.\n\nEstão autorizados a usar o sistema todos os chefes de serviço, coordenadores e diretores de secretaria, sendo que as demandas apresentadas por cada um devem ser aprovadas pelos órgãos superiores, até chegar ao titular da secretaria, que tem a prerrogativa do envio ao ILB das demandas por ele ratificadas.\n\nEm caso de substituição ou ausência do titular da unidade, ou mesmo do interesse de delegação deste preenchimento para outro servidor, favor entrar em contato pelo e-mail capacita_suporte@interlegis.leg.br para que possamos providenciar a autorização.\n\nAlgumas orientações para uso do sistema podem ser vistas em https://capacita.interlegis.leg.br/manual. Em caso de dúvidas, também estou disponível no ramal 5962.\n\nAtenciosamente\n\nMatheus Garcia Barbosa de Figueiredo\nAnalista de Sistemas - Tel (61) 3303-5962\nServiço de Pesquisa e Desenvolvimento Tecnológico - SPDT\nCoordenação de Tecnologia da Informação - COTIN\nSenado Federal / ILB / Interlegis"""),
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('capacitaApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDestinatarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TipoNotificacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='profile',
            name='orgao_ativo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orgao.Orgao'),
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remetente', models.CharField(max_length=34)),
                ('cc', models.CharField(blank=True, max_length=100)),
                ('assunto', models.CharField(max_length=100)),
                ('mensagem', models.TextField()),
                ('destinatarios', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='capacitaApp.TipoDestinatarios')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='capacitaApp.TipoNotificacao')),
            ],
            options={
                'ordering': ['tipo'],
            },
        ),
        migrations.RunPython(cria_tipos_notificacao),
        migrations.RunPython(cria_tipos_destinatarios),
        migrations.RunPython(cria_notificacoes),
    ]
