# Generated by Django 2.1.4 on 2018-12-14 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capacitaApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nivel',
            name='ind_excluido',
        ),
    ]
