# Generated by Django 2.1.4 on 2018-12-14 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacitaApp', '0002_remove_nivel_ind_excluido'),
    ]

    operations = [
        migrations.AddField(
            model_name='nivel',
            name='ind_excluido',
            field=models.NullBooleanField(default=False),
        ),
    ]
