# Generated by Django 2.1.3 on 2018-11-19 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capacitaApp', '0002_auto_20181119_1630'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mes',
        ),
    ]
