# Generated by Django 2.1.3 on 2018-11-19 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capacitaApp', '0003_delete_mes'),
    ]

    operations = [
        migrations.AddField(
            model_name='necessidade',
            name='cod_orgao',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='capacitaApp.Orgao'),
            preserve_default=False,
        ),
    ]
