# Generated by Django 2.1.4 on 2018-12-18 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgao', '0001_initial'),
        ('capacitaApp', '0003_nivel_ind_excluido'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='orgaos_vinculados',
            field=models.ManyToManyField(related_name='orgaos_vinculados', to='orgao.Orgao'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='orgao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orgao_id', to='orgao.Orgao'),
        ),
    ]
