# Generated by Django 2.1.3 on 2018-11-20 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacitaApp', '0004_necessidade_cod_orgao'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoTreinamento',
            fields=[
                ('cod_tipo_treinamento', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=900)),
                ('ind_excluido', models.NullBooleanField(default=False)),
            ],
            options={
                'db_table': 'tipo_treinamento',
                'ordering': ['nome'],
            },
        ),
    ]
