# Generated by Django 2.1.4 on 2018-12-27 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgao', '0001_initial'),
        ('capacitaApp', '0005_remove_profile_permissao_necessidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgaoPermissao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacitaApp.AuthGroup')),
                ('orgao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orgao_id', to='orgao.Orgao')),
            ],
            options={
                'db_table': 'orgao_permissao',
            },
        ),
        migrations.RemoveField(
            model_name='permissao',
            name='cod_orgao',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='orgao',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='orgaos_vinculados',
        ),
        migrations.DeleteModel(
            name='Permissao',
        ),
        migrations.AddField(
            model_name='profile',
            name='orgao_permissao',
            field=models.ManyToManyField(related_name='orgao_permissao', to='capacitaApp.OrgaoPermissao'),
        ),
    ]
