# Generated by Django 2.1.3 on 2018-11-20 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capacitaApp', '0005_tipotreinamento'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TipoTreinamento',
            new_name='Tipo_Treinamento',
        ),
    ]
