# Generated by Django 2.1.4 on 2018-12-27 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capacitaApp', '0006_auto_20181227_1338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='orgao_permissao',
            new_name='orgaos',
        ),
    ]
