# Generated by Django 2.1.3 on 2018-11-20 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capacitaApp', '0006_auto_20181120_1623'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipo_treinamento',
            options={},
        ),
        migrations.RemoveField(
            model_name='tipo_treinamento',
            name='ind_excluido',
        ),
        migrations.AddField(
            model_name='necessidade',
            name='cod_tipo_treinamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='capacitaApp.Tipo_Treinamento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='area_conhecimento',
            name='txt_descricao',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='nome',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='modalidade_treinamento',
            name='nome',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='necessidade',
            name='cod_area_conhecimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='capacitaApp.Area_Conhecimento'),
        ),
        migrations.AlterField(
            model_name='necessidade',
            name='cod_modalidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='capacitaApp.Modalidade_Treinamento'),
        ),
        migrations.AlterField(
            model_name='necessidade',
            name='cod_nivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='capacitaApp.Nivel'),
        ),
        migrations.AlterField(
            model_name='necessidade',
            name='cod_objetivo_treinamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='capacitaApp.Objetivo_Treinamento'),
        ),
        migrations.AlterField(
            model_name='nivel',
            name='nome',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='objetivo_treinamento',
            name='nome',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='orgao',
            name='nome',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='plano_capacitacao',
            name='ano_plano_capacitacao',
            field=models.DecimalField(decimal_places=0, max_digits=4, unique=True),
        ),
        migrations.AlterField(
            model_name='prioridade',
            name='nome',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='tipo_treinamento',
            name='nome',
            field=models.CharField(max_length=900, unique=True),
        ),
        migrations.AlterField(
            model_name='treinamento',
            name='nome',
            field=models.CharField(max_length=900, unique=True),
        ),
    ]
