# Generated by Django 2.1.3 on 2018-11-20 21:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacitaApp', '0007_auto_20181120_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='necessidade',
            name='hor_duracao',
            field=models.DecimalField(decimal_places=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
