# Generated by Django 2.1.4 on 2018-12-28 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgao', '0001_initial'),
        ('capacitaApp', '0007_auto_20181227_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='orgao_ativo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orgao.Orgao'),
        ),
    ]
