# Generated by Django 2.1.4 on 2018-12-28 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacitaApp', '0008_profile_orgao_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
