# Generated by Django 2.1.4 on 2019-01-11 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capacitaApp', '0009_profile_is_admin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user']},
        ),
    ]
