# Generated by Django 2.1.4 on 2019-02-12 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacitaApp', '0010_auto_20190111_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='orgaos',
            field=models.ManyToManyField(related_name='orgao_gestor', to='orgao.Orgao'),
        ),
    ]
