# Generated by Django 2.1.4 on 2019-02-15 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capacitaApp', '0012_auto_20190212_1441'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user__username']},
        ),
    ]
