# Generated by Django 2.2.6 on 2019-10-03 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treinamento',
            fields=[
                ('cod_treinamento', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=900, unique=True)),
                ('ind_excluido', models.BooleanField(default=False)),
                ('cod_area_conhecimento', models.ForeignKey(default='0', on_delete=django.db.models.deletion.DO_NOTHING, to='areas.Area_Conhecimento')),
            ],
            options={
                'db_table': 'treinamento',
                'ordering': ['nome'],
            },
        ),
    ]
